rails_tutorial: "https://www.railstutorial.org/"
rails: "https://rubyonrails.org/"
michaelhartl: "https://www.michaelhartl.com/"
rails_news: "https://news.railstutorial.org/"
rails_contact: "https://www.railstutorial.org/#contact"
rails_help: "https://github.com/mhartl/sample_app_6th_ed/blob/main/HELP.md"
rails_book: "https://www.railstutorial.org/book"
learn_enough: "https://www.learnenough.com/"
rails_screen_casts: "https://screencasts.railstutorial.org/"
