require('@rails/ujs').start()
require('turbolinks').start()
require('@rails/activestorage').start()
require('channels')
require('jquery')
require('./image.js')
require('i18n')
require('i18n.js')
require('i18n/translations')
import 'bootstrap'
